/*
 * ESS Manager dashboard cards (as of v0.4.4) - loaded automatically by the
 * integration, shown in the dashboard's "Add card" picker:
 *
 *   custom:ess-manager-battery-card   battery forecast chart
 *   custom:ess-manager-price-card     price chart (buy / sell / transport)
 *   custom:ess-manager-status-card    planned charge / discharge, price alerts, status history
 *
 * Each card only needs `entity:` - the installation's Status sensor - and
 * builds the same card as the example in dashboard/ of the repository. The
 * battery card has options on top (as of v0.5.0): show_<item> / legend_<item>
 * / color_<item> for each of its 11 items, legend, axis_titles, height, hours.
 * The price card: legend_<item> / color_<item> / labels_<item>, legend.
 * The charts are drawn by apexcharts-card; the status card uses
 * stack-in-card and multiple-entity-row (all three from HACS).
 *
 * GENERATED by tools/build_cards.py from tools/cards_template.js and the
 * dashboard/*.yaml examples - edit those, then run the script.
 */

const ESS_DOMAIN = "ess_manager";
const STATUS_PLACEHOLDER = "sensor.ess_manager_status";
const SIBLING_PREFIX = "sensor.ess_manager_";

// @@TEMPLATES@@

// -- Battery card options (as of v0.5.0) ---------------------------------------
// Every item can be hidden (show_<key>: false), kept out of the legend
// (legend_<key>: false) or given its own colour (color_<key>); plus the
// legend as a whole, the height, how many hours ahead and the axis titles.
// Everything defaults to the example card.
const BATTERY_ITEMS = [
  ["buy", "Buy"],
  ["balancing", "Balancing"],
  ["sell", "Sell"],
  ["solar_export", "Solar export"],
  ["lower_limit", "Lower limit"],
  ["upper_limit", "Upper limit"],
  ["planning_horizon", "Planning horizon"],
  ["solar", "Solar"],
  ["usage", "Usage"],
  ["soc", "SOC"],
  ["soc_new", "SOC new"],
];
// Colours: color_<key> as [r, g, b] (what the card editor's colour picker
// gives) or a "#rrggbb" string in YAML; the default is the example's colour.
const NAMED_COLORS = { green: "#008000", yellow: "#ffff00", red: "#ff0000", blue: "#0000ff", orange: "#ffa500", purple: "#800080" };
function hexToRgb(hex) {
  const text = String(hex || "").trim();
  const m = /^#?([0-9a-f]{2})([0-9a-f]{2})([0-9a-f]{2})$/i.exec(NAMED_COLORS[text.toLowerCase()] || text);
  return m ? [parseInt(m[1], 16), parseInt(m[2], 16), parseInt(m[3], 16)] : null;
}
function toHex(color) {
  if (Array.isArray(color) && color.length === 3) {
    return "#" + color.map((c) => Math.min(Math.max(Math.round(Number(c) || 0), 0), 255).toString(16).padStart(2, "0")).join("");
  }
  return hexToRgb(color) ? "#" + String(color).trim().replace(/^#/, "") : null;
}
const BATTERY_DEFAULTS = { legend: true, axis_titles: true, height: 270, hours: 120 };
for (const [key, name] of BATTERY_ITEMS) {
  BATTERY_DEFAULTS["show_" + key] = true;
  BATTERY_DEFAULTS["legend_" + key] = true;
  const serie = TEMPLATES.battery.cards[0].series.find((x) => x.name === name);
  const rgb = serie && hexToRgb(serie.color);
  if (rgb) BATTERY_DEFAULTS["color_" + key] = rgb;
}
const BATTERY_LABELS = {
  legend: "Show the legend",
  axis_titles: "Show the axis titles",
  height: "Height (px)",
  hours: "Hours ahead",
};
for (const [key, name] of BATTERY_ITEMS) {
  BATTERY_LABELS["show_" + key] = "Show";
  BATTERY_LABELS["legend_" + key] = "In the legend";
  BATTERY_LABELS["color_" + key] = "Colour";
}
const BATTERY_SCHEMA = [
  {
    type: "grid",
    name: "",
    schema: [
      { name: "legend", selector: { boolean: {} } },
      { name: "axis_titles", selector: { boolean: {} } },
      { name: "height", selector: { number: { min: 150, max: 800, step: 10, mode: "box", unit_of_measurement: "px" } } },
      { name: "hours", selector: { number: { min: 6, max: 120, step: 6, mode: "box", unit_of_measurement: "h" } } },
    ],
  },
  // One collapsible section per item: show, in the legend, colour.
  ...BATTERY_ITEMS.map(([key, name]) => ({
    type: "expandable",
    flatten: true,
    name: "item_" + key,
    title: name,
    schema: [
      {
        type: "grid",
        name: "",
        schema: [
          { name: "show_" + key, selector: { boolean: {} } },
          { name: "legend_" + key, selector: { boolean: {} } },
        ],
      },
      { name: "color_" + key, selector: { color_rgb: {} } },
    ],
  })),
];

function batteryKey(seriesName) {
  const found = BATTERY_ITEMS.find(([, name]) => name === seriesName);
  return found ? found[0] : null;
}

function applyBatteryOptions(card, config) {
  const opt = { ...BATTERY_DEFAULTS, ...config };
  const chart = card.cards[0];
  chart.series = chart.series
    .filter((serie) => {
      const key = batteryKey(serie.name);
      return !key || opt["show_" + key] !== false;
    })
    .map((serie) => {
      const key = batteryKey(serie.name);
      if (key && opt["legend_" + key] === false) {
        serie.show = { ...(serie.show || {}), in_legend: false };
      }
      const color = key && config["color_" + key] !== undefined ? toHex(config["color_" + key]) : null;
      if (color) serie.color = color;
      return serie;
    });
  // An axis without any series left is dropped (apexcharts-card refuses it).
  const used = new Set(chart.series.map((serie) => serie.yaxis_id));
  chart.yaxis = (chart.yaxis || []).filter((axis) => used.has(axis.id));
  if (opt.axis_titles === false) {
    for (const axis of chart.yaxis) {
      if (axis.apex_config) delete axis.apex_config.title;
    }
  }
  const hours = Math.min(Math.max(Math.round(Number(opt.hours) || 120), 1), 120);
  chart.graph_span = `${hours}h`;
  chart.apex_config = chart.apex_config || {};
  chart.apex_config.chart = { ...(chart.apex_config.chart || {}), height: `${Math.round(Number(opt.height) || 270)}px` };
  if (opt.legend === false) chart.apex_config.legend = { ...(chart.apex_config.legend || {}), show: false };
  return card;
}

// -- Price card options (as of v0.5.0) -----------------------------------------
// Per item: in the legend (legend_<key>), colour (color_<key>) and - where
// the card has them - its price labels (labels_<key>: the lowest buy price,
// the highest sell price, today's / tomorrow's min and max); plus the
// legend as a whole. The items aren't hideable themselves: the price
// blocks fit together, hiding one would leave a gap.
const PRICE_ITEMS = [
  ["transport", "Incl. transport"],
  ["buy", "Buy"],
  ["sell", "Sell"],
  ["solar_export", "Solar export"],
  ["today", "Today's prices"],
  ["tomorrow", "Tomorrow's prices"],
];
const PRICE_LABEL_ITEMS = { buy: "Lowest price label", sell: "Highest price label", today: "Min / max labels", tomorrow: "Min / max labels" };
const PRICE_DEFAULTS = { legend: true };
const PRICE_LABELS = { legend: "Show the legend" };
for (const [key, name] of PRICE_ITEMS) {
  PRICE_DEFAULTS["legend_" + key] = true;
  PRICE_LABELS["legend_" + key] = "In the legend";
  PRICE_LABELS["color_" + key] = "Colour";
  const serie = TEMPLATES.price.cards[0].series.find((x) => x.name === name);
  const rgb = serie && hexToRgb(serie.color);
  if (rgb) PRICE_DEFAULTS["color_" + key] = rgb;
  if (PRICE_LABEL_ITEMS[key]) {
    PRICE_DEFAULTS["labels_" + key] = true;
    PRICE_LABELS["labels_" + key] = PRICE_LABEL_ITEMS[key];
  }
}
const PRICE_SCHEMA = [
  { name: "legend", selector: { boolean: {} } },
  ...PRICE_ITEMS.map(([key, name]) => ({
    type: "expandable",
    flatten: true,
    name: "item_" + key,
    title: name,
    schema: [
      {
        type: "grid",
        name: "",
        schema: [
          { name: "legend_" + key, selector: { boolean: {} } },
          ...(PRICE_LABEL_ITEMS[key] ? [{ name: "labels_" + key, selector: { boolean: {} } }] : []),
        ],
      },
      { name: "color_" + key, selector: { color_rgb: {} } },
    ],
  })),
];

function applyPriceOptions(card, config) {
  const opt = { ...PRICE_DEFAULTS, ...config };
  const chart = card.cards[0];
  // Today's / tomorrow's min-max labels sit on two invisible helper lines
  // (the unnamed series with extremas), in that order.
  const helpers = chart.series.filter((serie) => serie.show && serie.show.extremas === true && serie.color === "transparent");
  const helperKey = new Map([[helpers[0], "today"], [helpers[1], "tomorrow"]]);
  for (const serie of chart.series) {
    const item = PRICE_ITEMS.find(([, name]) => name === serie.name);
    const key = item ? item[0] : helperKey.get(serie);
    if (!key) continue;
    if (item) {
      if (opt["legend_" + key] === false) serie.show = { ...(serie.show || {}), in_legend: false };
      const color = config["color_" + key] !== undefined ? toHex(config["color_" + key]) : null;
      if (color) serie.color = color;
    }
    const labelsOnThis = key === "buy" || key === "sell" ? !!item : !item;
    if (labelsOnThis && opt["labels_" + key] === false && serie.show) {
      serie.show = { ...serie.show };
      delete serie.show.extremas;
    }
  }
  if (opt.legend === false) {
    chart.apex_config = chart.apex_config || {};
    chart.apex_config.legend = { ...(chart.apex_config.legend || {}), show: false };
  }
  return card;
}

const CARDS = {
  "ess-manager-battery-card": {
    name: "ESS Manager - Battery forecast",
    description: "The battery forecast for the coming days, with the planned buy / sell windows.",
    template: TEMPLATES.battery,
    requires: ["apexcharts-card"],
    size: 6,
    schema: BATTERY_SCHEMA,
    defaults: BATTERY_DEFAULTS,
    labels: BATTERY_LABELS,
    apply: applyBatteryOptions,
  },
  "ess-manager-price-card": {
    name: "ESS Manager - Prices",
    description: "Today's and tomorrow's prices, with the buy / sell windows and transport.",
    template: TEMPLATES.price,
    requires: ["apexcharts-card"],
    size: 5,
    schema: PRICE_SCHEMA,
    defaults: PRICE_DEFAULTS,
    labels: PRICE_LABELS,
    apply: applyPriceOptions,
  },
  "ess-manager-status-card": {
    name: "ESS Manager - Status",
    description: "The planned charge and discharge, the price alerts and the status history.",
    template: TEMPLATES.status,
    requires: ["stack-in-card", "multiple-entity-row"],
    size: 6,
  },
};

// Replace the example's placeholder entity_ids with this installation's own:
// the Status sensor, and its sibling sensors by key (from the Status
// sensor's `card_entities` attribute).
function substitute(value, entity, siblings) {
  if (Array.isArray(value)) return value.map((v) => substitute(v, entity, siblings));
  if (value && typeof value === "object") {
    const out = {};
    for (const [k, v] of Object.entries(value)) out[k] = substitute(v, entity, siblings);
    return out;
  }
  if (typeof value === "string") {
    if (value === STATUS_PLACEHOLDER) return entity;
    if (value.startsWith(SIBLING_PREFIX)) {
      const key = value.slice(SIBLING_PREFIX.length);
      if (siblings && siblings[key]) return siblings[key];
    }
  }
  return value;
}

function isStatusSensor(stateObj) {
  return !!(stateObj && stateObj.attributes && "all_price" in stateObj.attributes && "battery_forecast" in stateObj.attributes);
}

function findStatusSensor(hass) {
  return Object.keys((hass && hass.states) || {}).find(
    (id) => id.startsWith("sensor.") && isStatusSensor(hass.states[id])
  );
}

function whenDefined(tag, ms) {
  if (customElements.get(tag)) return Promise.resolve(true);
  return Promise.race([
    customElements.whenDefined(tag).then(() => true),
    new Promise((resolve) => setTimeout(() => resolve(false), ms)),
  ]);
}

class EssManagerCard extends HTMLElement {
  static get info() {
    return CARDS[this.cardType];
  }

  setConfig(config) {
    if (!config || !config.entity) {
      throw new Error("Choose the ESS Manager Status sensor (entity)");
    }
    this._config = config;
    this._builtFor = null;
    this._build();
  }

  set hass(hass) {
    this._hass = hass;
    if (this._card) this._card.hass = hass;
    this._build();
  }

  getCardSize() {
    if (this._card && typeof this._card.getCardSize === "function") return this._card.getCardSize();
    return this.constructor.info.size;
  }

  static getStubConfig(hass) {
    return { entity: findStatusSensor(hass) || "" };
  }

  static getConfigElement() {
    const editor = document.createElement("ess-manager-card-editor");
    editor.cardInfo = this.info;
    return editor;
  }

  _message(text) {
    const card = document.createElement("ha-card");
    const div = document.createElement("div");
    div.style.padding = "16px";
    div.textContent = text;
    card.appendChild(div);
    this.replaceChildren(card);
    this._card = null;
  }

  async _build() {
    if (!this._hass || !this._config) return;
    const entity = this._config.entity;
    const stateObj = this._hass.states[entity];
    const siblings = (stateObj && stateObj.attributes && stateObj.attributes.card_entities) || {};
    const key = JSON.stringify([this._config, siblings]);
    if (this._builtFor === key || this._building) return;
    this._building = true;
    try {
      const info = this.constructor.info;
      if (!stateObj) {
        this._message(`ESS Manager: ${entity} not found.`);
        return;
      }
      if (!isStatusSensor(stateObj)) {
        this._message(`ESS Manager: ${entity} is not an ESS Manager Status sensor - choose the "Status" sensor.`);
        return;
      }
      const missing = [];
      for (const tag of info.requires) {
        if (!(await whenDefined(tag, 5000))) missing.push(tag);
      }
      if (missing.length) {
        this._message(`ESS Manager: this card needs ${missing.join(" and ")} - install it from HACS (Frontend), then reload the page.`);
        this._builtFor = null;
        return;
      }
      let config = substitute(info.template, entity, siblings);
      if (info.apply) config = info.apply(config, this._config);
      const helpers = await window.loadCardHelpers();
      const card = helpers.createCardElement(config);
      card.hass = this._hass;
      this.replaceChildren(card);
      this._card = card;
      this._builtFor = key;
    } finally {
      this._building = false;
    }
  }
}

class EssManagerCardEditor extends HTMLElement {
  setConfig(config) {
    this._config = config;
    this._render();
  }

  set hass(hass) {
    this._hass = hass;
    this._render();
  }

  _render() {
    if (!this._hass || !this._config) return;
    const info = this.cardInfo || {};
    const defaults = info.defaults || {};
    const labels = { entity: "ESS Manager Status sensor", ...(info.labels || {}) };
    if (!this._form) {
      this._form = document.createElement("ha-form");
      this._form.computeLabel = (field) => labels[field.name] || field.title || field.name;
      this._form.addEventListener("value-changed", (ev) => {
        // Only what differs from the defaults ends up in the card's YAML.
        const config = { ...this._config, ...ev.detail.value };
        for (const [key, value] of Object.entries(defaults)) {
          if (JSON.stringify(config[key]) === JSON.stringify(value)) delete config[key];
        }
        this.dispatchEvent(new CustomEvent("config-changed", { detail: { config }, bubbles: true, composed: true }));
      });
      this.appendChild(this._form);
    }
    this._form.hass = this._hass;
    this._form.schema = [
      { name: "entity", required: true, selector: { entity: { filter: { integration: ESS_DOMAIN, domain: "sensor" } } } },
      ...(info.schema || []),
    ];
    this._form.data = { ...defaults, ...this._config };
  }
}

if (!customElements.get("ess-manager-card-editor")) {
  customElements.define("ess-manager-card-editor", EssManagerCardEditor);
}
window.customCards = window.customCards || [];
for (const [type, info] of Object.entries(CARDS)) {
  if (customElements.get(type)) continue;
  customElements.define(type, class extends EssManagerCard {
    static get cardType() {
      return type;
    }
  });
  window.customCards.push({
    type,
    name: info.name,
    description: info.description,
    preview: true,
    documentationURL: "https://github.com/MisterX-RC/ESS-manager-HA#dashboard",
  });
}
console.info("%c ESS Manager cards %c loaded ", "color:#fff;background:#4caf50", "");
