/*
 * ESS Manager dashboard cards (as of v0.4.4) - loaded automatically by the
 * integration, shown in the dashboard's "Add card" picker:
 *
 *   custom:ess-manager-battery-card   battery forecast chart
 *   custom:ess-manager-price-card     price chart (buy / sell / transport)
 *   custom:ess-manager-status-card    planned charge / discharge, price alerts, status history
 *
 * Each card only needs `entity:` - the installation's Status sensor - and
 * builds the same card as the example in dashboard/ of the repository.
 * The charts are drawn by apexcharts-card; the status card uses
 * stack-in-card and multiple-entity-row (all three from HACS).
 *
 * GENERATED by tools/build_cards.py from tools/cards_template.js and the
 * dashboard/*.yaml examples - edit those, then run the script.
 */

const ESS_DOMAIN = "ess_manager";
const STATUS_PLACEHOLDER = "sensor.ess_manager_status";
const SIBLING_PREFIX = "sensor.ess_manager_";

// @@TEMPLATES@@

const CARDS = {
  "ess-manager-battery-card": {
    name: "ESS Manager - Battery forecast",
    description: "The battery forecast for the coming days, with the planned buy / sell windows.",
    template: TEMPLATES.battery,
    requires: ["apexcharts-card"],
    size: 6,
  },
  "ess-manager-price-card": {
    name: "ESS Manager - Prices",
    description: "Today's and tomorrow's prices, with the buy / sell windows and transport.",
    template: TEMPLATES.price,
    requires: ["apexcharts-card"],
    size: 5,
  },
  "ess-manager-status-card": {
    name: "ESS Manager - Status",
    description: "The planned charge and discharge, the price alerts and the status history.",
    template: TEMPLATES.status,
    requires: ["stack-in-card", "multiple-entity-row"],
    size: 6,
  },
};

// Replace the example's placeholder entity_ids with this installation's own:
// the Status sensor, and its sibling sensors by key (from the Status
// sensor's `card_entities` attribute).
function substitute(value, entity, siblings) {
  if (Array.isArray(value)) return value.map((v) => substitute(v, entity, siblings));
  if (value && typeof value === "object") {
    const out = {};
    for (const [k, v] of Object.entries(value)) out[k] = substitute(v, entity, siblings);
    return out;
  }
  if (typeof value === "string") {
    if (value === STATUS_PLACEHOLDER) return entity;
    if (value.startsWith(SIBLING_PREFIX)) {
      const key = value.slice(SIBLING_PREFIX.length);
      if (siblings && siblings[key]) return siblings[key];
    }
  }
  return value;
}

function isStatusSensor(stateObj) {
  return !!(stateObj && stateObj.attributes && "all_price" in stateObj.attributes && "battery_forecast" in stateObj.attributes);
}

function findStatusSensor(hass) {
  return Object.keys((hass && hass.states) || {}).find(
    (id) => id.startsWith("sensor.") && isStatusSensor(hass.states[id])
  );
}

function whenDefined(tag, ms) {
  if (customElements.get(tag)) return Promise.resolve(true);
  return Promise.race([
    customElements.whenDefined(tag).then(() => true),
    new Promise((resolve) => setTimeout(() => resolve(false), ms)),
  ]);
}

class EssManagerCard extends HTMLElement {
  static get info() {
    return CARDS[this.cardType];
  }

  setConfig(config) {
    if (!config || !config.entity) {
      throw new Error("Choose the ESS Manager Status sensor (entity)");
    }
    this._config = config;
    this._builtFor = null;
    this._build();
  }

  set hass(hass) {
    this._hass = hass;
    if (this._card) this._card.hass = hass;
    this._build();
  }

  getCardSize() {
    if (this._card && typeof this._card.getCardSize === "function") return this._card.getCardSize();
    return this.constructor.info.size;
  }

  static getStubConfig(hass) {
    return { entity: findStatusSensor(hass) || "" };
  }

  static getConfigElement() {
    return document.createElement("ess-manager-card-editor");
  }

  _message(text) {
    const card = document.createElement("ha-card");
    const div = document.createElement("div");
    div.style.padding = "16px";
    div.textContent = text;
    card.appendChild(div);
    this.replaceChildren(card);
    this._card = null;
  }

  async _build() {
    if (!this._hass || !this._config) return;
    const entity = this._config.entity;
    const stateObj = this._hass.states[entity];
    const siblings = (stateObj && stateObj.attributes && stateObj.attributes.card_entities) || {};
    const key = entity + "|" + JSON.stringify(siblings);
    if (this._builtFor === key || this._building) return;
    this._building = true;
    try {
      const info = this.constructor.info;
      if (!stateObj) {
        this._message(`ESS Manager: ${entity} not found.`);
        return;
      }
      if (!isStatusSensor(stateObj)) {
        this._message(`ESS Manager: ${entity} is not an ESS Manager Status sensor - choose the "Status" sensor.`);
        return;
      }
      const missing = [];
      for (const tag of info.requires) {
        if (!(await whenDefined(tag, 5000))) missing.push(tag);
      }
      if (missing.length) {
        this._message(`ESS Manager: this card needs ${missing.join(" and ")} - install it from HACS (Frontend), then reload the page.`);
        this._builtFor = null;
        return;
      }
      const config = substitute(info.template, entity, siblings);
      const helpers = await window.loadCardHelpers();
      const card = helpers.createCardElement(config);
      card.hass = this._hass;
      this.replaceChildren(card);
      this._card = card;
      this._builtFor = key;
    } finally {
      this._building = false;
    }
  }
}

class EssManagerCardEditor extends HTMLElement {
  setConfig(config) {
    this._config = config;
    this._render();
  }

  set hass(hass) {
    this._hass = hass;
    this._render();
  }

  _render() {
    if (!this._hass || !this._config) return;
    if (!this._form) {
      this._form = document.createElement("ha-form");
      this._form.computeLabel = () => "ESS Manager Status sensor";
      this._form.addEventListener("value-changed", (ev) => {
        const config = { ...this._config, ...ev.detail.value };
        this.dispatchEvent(new CustomEvent("config-changed", { detail: { config }, bubbles: true, composed: true }));
      });
      this.appendChild(this._form);
    }
    this._form.hass = this._hass;
    this._form.schema = [
      { name: "entity", required: true, selector: { entity: { filter: { integration: ESS_DOMAIN, domain: "sensor" } } } },
    ];
    this._form.data = this._config;
  }
}

if (!customElements.get("ess-manager-card-editor")) {
  customElements.define("ess-manager-card-editor", EssManagerCardEditor);
}
window.customCards = window.customCards || [];
for (const [type, info] of Object.entries(CARDS)) {
  if (customElements.get(type)) continue;
  customElements.define(type, class extends EssManagerCard {
    static get cardType() {
      return type;
    }
  });
  window.customCards.push({
    type,
    name: info.name,
    description: info.description,
    preview: true,
    documentationURL: "https://github.com/MisterX-RC/ESS-manager-HA#dashboard",
  });
}
console.info("%c ESS Manager cards %c loaded ", "color:#fff;background:#4caf50", "");
