alias: ESS manager
description: ''
triggers:
  - trigger: state
    entity_id:
      - sensor.ess_manager
    to:
      - Stop
      - Standby
      - Grid usage
      - Solar export
      - unknown
    id: Idle
  - trigger: state
    entity_id:
      - sensor.ess_manager
    to:
      - Start charge
    id: Start charge
  - trigger: state
    entity_id:
      - sensor.ess_manager
    to:
      - Start discharge
    id: Start discharge
  - trigger: state
    entity_id:
      - sensor.ess_manager
    to:
      - Start negative price charge
    id: Start negative price charge
  - trigger: state
    entity_id:
      - sensor.ess_manager
    to:
      - Start spike discharge
    id: Start spike discharge
conditions: []
actions:
  - choose:
      - conditions:
          - condition: trigger
            id:
              - Idle
        sequence:
          - action: input_number.set_value
            metadata: {}
            data:
              value: 0
            target:
              entity_id: input_number.victron_ess_setpoint
      - conditions:
          - condition: trigger
            id:
              - Start charge
        sequence:
          - action: input_number.set_value
            metadata: {}
            data:
              value: '{{ 7 }}'
            target:
              entity_id: input_number.victron_ess_setpoint
      - conditions:
          - condition: trigger
            id:
              - Start discharge
        sequence:
          - action: input_number.set_value
            metadata: {}
            data:
              value: '{{ -10 }}'
            target:
              entity_id: input_number.victron_ess_setpoint
      - conditions:
          - condition: trigger
            id:
              - Start negative price charge
        sequence:
          - action: input_number.set_value
            metadata: {}
            data:
              value: '{{ 15 }}'
            target:
              entity_id: input_number.victron_ess_setpoint
      - conditions:
          - condition: trigger
            id:
              - Start spike discharge
        sequence:
          - action: input_number.set_value
            metadata: {}
            data:
              value: '{{ -15 }}'
            target:
              entity_id: input_number.victron_ess_setpoint
    enabled: true
mode: restart
